### PR TITLE
Create, delete, and update support.

### PR DESCRIPTION
**Pull request by zarathustra323**
Full CRUD is now operational for attributes at the persistence/store level under the new Model/Store structure.

### CODE REVIEW

**Comment by solocommand** [comment]
`model-power`?

**Comment by zarathustra323** [comment]
You betcha!! The core model object has most of the "power" now :)

**Comment by solocommand** [comment]
lol, gotcha. I was thinking more along the lines of `by the power of greyskull!`

**Comment by zarathustra323** [comment]
That works, too :)

**Pull request merged**
